### PR TITLE
Bug/issue 44 15

### LINKED ISSUE #44: Error when the rule name is longer than 988 characters
### Creating rule ###
* Request
```
url: (POST  http://10.95.169.246:9090/rules)
 
Header: {'Fiware-Service': 'unknownT', 'Content-Type': 'application/json', 'Fiware-ServicePath': u'/', 'Accept': 'application/json'}
 
Body: {"action": {"type": "<rule_type>", "template": "Element ${Meter} has value <<<${attrName_0_var}>>> \n -- <template_info>", "parameters": null}, "text": "select *,\"ZwMCOdUoGsxqKR0VrFeqbDPmz7PUEfl0hH9PDPlb2gje0P1vouScgvAzFTfOYuLacF5T9ZN82hTZQ1tvRzR73N8aXBj9zb7alCqePOpMKGEHFIi5zKGRIGcFpimtVgc2udIsiFoPogKe9cMohQHOpQc3zEbZs5dsGc8pJUAPncmU0FAyTX8u97t0H3xrmS1OfL4zLpU16phzjLdzRoKgn32c69hJTlNbkK9J7h2oM9Wia80mRYiNKN1CwFRYqEFRynrOJ2oxgePFcTaEy20FqqhIdpJrVfMquUdd8Ax41JbUDeXXvORgFBnukTkRUGzrhTy58zDHcCTpHPoCb5lU9M5OlcE97OXS6fyJk9slh6C7Wq7YuInaJRBxepGn7ndRGghP8ejL5lyQlrM3hIaYyZg1Qb7vu7pXcsAurZ720UGICYmr5QJQGdfESwRZcozfbc2pldUrpLi5pFCdO28P2O2cH76o4oIFAY4rOPxFGBOMwudc8KwWtWybhxAKe9oa5U21wuD3fjgGX6zfwu21E7aFdopztkPxyyP8mIzaRNUDjB2rY6CzRiy8PqD82QL0if0l2HjDFnxjkmAXt4UE9lIP7TlR0ZmPijA1mZ43052v37WSjJ0X0fsLy573zMpixrqy7DfeCmyCWjmjk9MrViHfSFdNg5tfTQPzeVbXoK8mdg4odZKcPGV2tKoYzCxKw6PjPtXrcVx789z4LRtLYG5TX1c3Q8a33PYxARkEYJj6uYd5c9aF6azWDTLMB0FjZjouO8NYbLiVp2V3iuwLj4TpQhoUb4DPMqxaNKkp7b7nPrWhPuY3e4Og20c2aHCSzMZcrZGlltqKXKH6adOeZzOgj69C7QkBP2OX8iMAzTE2li0bXEIV5HFxwYpzQcy7N1ASilYppiWkF9wEc8JUJlk8PiSF3S8GC9FvNWkf3Kcmjz3FTNFzDmB9FQSQYxx9kivmOT1YOKna78DCZvgpiH0jVEmj\" as ruleName, \"/\" as service, \"unknownT\" as tenant, *, ev.attrName_0? as attrName_0_var, ev.id? as Meter from pattern [every ev=iotEvent(cast(cast(attrName_0?,String),float)>1.5 and type=\"Room\")]", "name": "ZwMCOdUoGsxqKR0VrFeqbDPmz7PUEfl0hH9PDPlb2gje0P1vouScgvAzFTfOYuLacF5T9ZN82hTZQ1tvRzR73N8aXBj9zb7alCqePOpMKGEHFIi5zKGRIGcFpimtVgc2udIsiFoPogKe9cMohQHOpQc3zEbZs5dsGc8pJUAPncmU0FAyTX8u97t0H3xrmS1OfL4zLpU16phzjLdzRoKgn32c69hJTlNbkK9J7h2oM9Wia80mRYiNKN1CwFRYqEFRynrOJ2oxgePFcTaEy20FqqhIdpJrVfMquUdd8Ax41JbUDeXXvORgFBnukTkRUGzrhTy58zDHcCTpHPoCb5lU9M5OlcE97OXS6fyJk9slh6C7Wq7YuInaJRBxepGn7ndRGghP8ejL5lyQlrM3hIaYyZg1Qb7vu7pXcsAurZ720UGICYmr5QJQGdfESwRZcozfbc2pldUrpLi5pFCdO28P2O2cH76o4oIFAY4rOPxFGBOMwudc8KwWtWybhxAKe9oa5U21wuD3fjgGX6zfwu21E7aFdopztkPxyyP8mIzaRNUDjB2rY6CzRiy8PqD82QL0if0l2HjDFnxjkmAXt4UE9lIP7TlR0ZmPijA1mZ43052v37WSjJ0X0fsLy573zMpixrqy7DfeCmyCWjmjk9MrViHfSFdNg5tfTQPzeVbXoK8mdg4odZKcPGV2tKoYzCxKw6PjPtXrcVx789z4LRtLYG5TX1c3Q8a33PYxARkEYJj6uYd5c9aF6azWDTLMB0FjZjouO8NYbLiVp2V3iuwLj4TpQhoUb4DPMqxaNKkp7b7nPrWhPuY3e4Og20c2aHCSzMZcrZGlltqKXKH6adOeZzOgj69C7QkBP2OX8iMAzTE2li0bXEIV5HFxwYpzQcy7N1ASilYppiWkF9wEc8JUJlk8PiSF3S8GC9FvNWkf3Kcmjz3FTNFzDmB9FQSQYxx9kivmOT1YOKna78DCZvgpiH0jVEmj"}
 ```
* Response
```
status code: 200
 
Header: {'content-length': '4987', 'unica-correlator': '9d35eb05-f8aa-48f6-8dc6-3b00a3b53a0f', 'x-content-type-options': 'nosniff', 'x-powered-by': 'Express', 'connection': 'keep-alive', 'date': 'Mon, 02 Feb 2015 09:26:02 GMT', 'content-type': 'application/json; charset=utf-8'}
 
Body: {"error":null,"data":[false,[{"code":200,"body":{"text":"create context ctxt$unknownt$ partition by tenant from iotEvent(tenant=\"unknownt\" and service=\"/\")","timeLastStateChange":1422868050718,"name":"ctxt$unknownt$","state":"STARTED"}},{"code":200,"body":{"text":"context ctxt$unknownt$ select *,\"ZwMCOdUoGsxqKR0VrFeqbDPmz7PUEfl0hH9PDPlb2gje0P1vouScgvAzFTfOYuLacF5T9ZN82hTZQ1tvRzR73N8aXBj9zb7alCqePOpMKGEHFIi5zKGRIGcFpimtVgc2udIsiFoPogKe9cMohQHOpQc3zEbZs5dsGc8pJUAPncmU0FAyTX8u97t0H3xrmS1OfL4zLpU16phzjLdzRoKgn32c69hJTlNbkK9J7h2oM9Wia80mRYiNKN1CwFRYqEFRynrOJ2oxgePFcTaEy20FqqhIdpJrVfMquUdd8Ax41JbUDeXXvORgFBnukTkRUGzrhTy58zDHcCTpHPoCb5lU9M5OlcE97OXS6fyJk9slh6C7Wq7YuInaJRBxepGn7ndRGghP8ejL5lyQlrM3hIaYyZg1Qb7vu7pXcsAurZ720UGICYmr5QJQGdfESwRZcozfbc2pldUrpLi5pFCdO28P2O2cH76o4oIFAY4rOPxFGBOMwudc8KwWtWybhxAKe9oa5U21wuD3fjgGX6zfwu21E7aFdopztkPxyyP8mIzaRNUDjB2rY6CzRiy8PqD82QL0if0l2HjDFnxjkmAXt4UE9lIP7TlR0ZmPijA1mZ43052v37WSjJ0X0fsLy573zMpixrqy7DfeCmyCWjmjk9MrViHfSFdNg5tfTQPzeVbXoK8mdg4odZKcPGV2tKoYzCxKw6PjPtXrcVx789z4LRtLYG5TX1c3Q8a33PYxARkEYJj6uYd5c9aF6azWDTLMB0FjZjouO8NYbLiVp2V3iuwLj4TpQhoUb4DPMqxaNKkp7b7nPrWhPuY3e4Og20c2aHCSzMZcrZGlltqKXKH6adOeZzOgj69C7QkBP2OX8iMAzTE2li0bXEIV5HFxwYpzQcy7N1ASilYppiWkF9wEc8JUJlk8PiSF3S8GC9FvNWkf3Kcmjz3FTNFzDmB9FQSQYxx9kivmOT1YOKna78DCZvgpiH0jVEmj\" as ruleName, \"/\" as service, \"unknownT\" as tenant, *, ev.attrName_0? as attrName_0_var, ev.id? as Meter from pattern [every ev=iotEvent(cast(cast(attrName_0?,String),float)>1.5 and type=\"Room\")]","timeLastStateChange":1422869162518,"name":"ZwMCOdUoGsxqKR0VrFeqbDPmz7PUEfl0hH9PDPlb2gje0P1vouScgvAzFTfOYuLacF5T9ZN82hTZQ1tvRzR73N8aXBj9zb7alCqePOpMKGEHFIi5zKGRIGcFpimtVgc2udIsiFoPogKe9cMohQHOpQc3zEbZs5dsGc8pJUAPncmU0FAyTX8u97t0H3xrmS1OfL4zLpU16phzjLdzRoKgn32c69hJTlNbkK9J7h2oM9Wia80mRYiNKN1CwFRYqEFRynrOJ2oxgePFcTaEy20FqqhIdpJrVfMquUdd8Ax41JbUDeXXvORgFBnukTkRUGzrhTy58zDHcCTpHPoCb5lU9M5OlcE97OXS6fyJk9slh6C7Wq7YuInaJRBxepGn7ndRGghP8ejL5lyQlrM3hIaYyZg1Qb7vu7pXcsAurZ720UGICYmr5QJQGdfESwRZcozfbc2pldUrpLi5pFCdO28P2O2cH76o4oIFAY4rOPxFGBOMwudc8KwWtWybhxAKe9oa5U21wuD3fjgGX6zfwu21E7aFdopztkPxyyP8mIzaRNUDjB2rY6CzRiy8PqD82QL0if0l2HjDFnxjkmAXt4UE9lIP7TlR0ZmPijA1mZ43052v37WSjJ0X0fsLy573zMpixrqy7DfeCmyCWjmjk9MrViHfSFdNg5tfTQPzeVbXoK8mdg4odZKcPGV2tKoYzCxKw6PjPtXrcVx789z4LRtLYG5TX1c3Q8a33PYxARkEYJj6uYd5c9aF6azWDTLMB0FjZjouO8NYbLiVp2V3iuwLj4TpQhoUb4DPMqxaNKkp7b7nPrWhPuY3e4Og20c2aHCSzMZcrZGlltqKXKH6adOeZzOgj69C7QkBP2OX8iMAzTE2li0bXEIV5HFxwYpzQcy7N1ASilYppiWkF9wEc8JUJlk8PiSF3S8GC9FvNWkf3Kcmjz3FTNFzDmB9FQSQYxx9kivmOT1YOKna78DCZvgpiH0jVEmj@unknownt/","state":"STARTED"}},null],{"action":{"type":"<rule_type>","template":"Element ${Meter} has value <<<${attrName_0_var}>>> \n -- <template_info>","parameters":null},"text":"select *,\"ZwMCOdUoGsxqKR0VrFeqbDPmz7PUEfl0hH9PDPlb2gje0P1vouScgvAzFTfOYuLacF5T9ZN82hTZQ1tvRzR73N8aXBj9zb7alCqePOpMKGEHFIi5zKGRIGcFpimtVgc2udIsiFoPogKe9cMohQHOpQc3zEbZs5dsGc8pJUAPncmU0FAyTX8u97t0H3xrmS1OfL4zLpU16phzjLdzRoKgn32c69hJTlNbkK9J7h2oM9Wia80mRYiNKN1CwFRYqEFRynrOJ2oxgePFcTaEy20FqqhIdpJrVfMquUdd8Ax41JbUDeXXvORgFBnukTkRUGzrhTy58zDHcCTpHPoCb5lU9M5OlcE97OXS6fyJk9slh6C7Wq7YuInaJRBxepGn7ndRGghP8ejL5lyQlrM3hIaYyZg1Qb7vu7pXcsAurZ720UGICYmr5QJQGdfESwRZcozfbc2pldUrpLi5pFCdO28P2O2cH76o4oIFAY4rOPxFGBOMwudc8KwWtWybhxAKe9oa5U21wuD3fjgGX6zfwu21E7aFdopztkPxyyP8mIzaRNUDjB2rY6CzRiy8PqD82QL0if0l2HjDFnxjkmAXt4UE9lIP7TlR0ZmPijA1mZ43052v37WSjJ0X0fsLy573zMpixrqy7DfeCmyCWjmjk9MrViHfSFdNg5tfTQPzeVbXoK8mdg4odZKcPGV2tKoYzCxKw6PjPtXrcVx789z4LRtLYG5TX1c3Q8a33PYxARkEYJj6uYd5c9aF6azWDTLMB0FjZjouO8NYbLiVp2V3iuwLj4TpQhoUb4DPMqxaNKkp7b7nPrWhPuY3e4Og20c2aHCSzMZcrZGlltqKXKH6adOeZzOgj69C7QkBP2OX8iMAzTE2li0bXEIV5HFxwYpzQcy7N1ASilYppiWkF9wEc8JUJlk8PiSF3S8GC9FvNWkf3Kcmjz3FTNFzDmB9FQSQYxx9kivmOT1YOKna78DCZvgpiH0jVEmj\" as ruleName, \"/\" as service, \"unknownT\" as tenant, *, ev.attrName_0? as attrName_0_var, ev.id? as Meter from pattern [every ev=iotEvent(cast(cast(attrName_0?,String),float)>1.5 and type=\"Room\")]","name":"ZwMCOdUoGsxqKR0VrFeqbDPmz7PUEfl0hH9PDPlb2gje0P1vouScgvAzFTfOYuLacF5T9ZN82hTZQ1tvRzR73N8aXBj9zb7alCqePOpMKGEHFIi5zKGRIGcFpimtVgc2udIsiFoPogKe9cMohQHOpQc3zEbZs5dsGc8pJUAPncmU0FAyTX8u97t0H3xrmS1OfL4zLpU16phzjLdzRoKgn32c69hJTlNbkK9J7h2oM9Wia80mRYiNKN1CwFRYqEFRynrOJ2oxgePFcTaEy20FqqhIdpJrVfMquUdd8Ax41JbUDeXXvORgFBnukTkRUGzrhTy58zDHcCTpHPoCb5lU9M5OlcE97OXS6fyJk9slh6C7Wq7YuInaJRBxepGn7ndRGghP8ejL5lyQlrM3hIaYyZg1Qb7vu7pXcsAurZ720UGICYmr5QJQGdfESwRZcozfbc2pldUrpLi5pFCdO28P2O2cH76o4oIFAY4rOPxFGBOMwudc8KwWtWybhxAKe9oa5U21wuD3fjgGX6zfwu21E7aFdopztkPxyyP8mIzaRNUDjB2rY6CzRiy8PqD82QL0if0l2HjDFnxjkmAXt4UE9lIP7TlR0ZmPijA1mZ43052v37WSjJ0X0fsLy573zMpixrqy7DfeCmyCWjmjk9MrViHfSFdNg5tfTQPzeVbXoK8mdg4odZKcPGV2tKoYzCxKw6PjPtXrcVx789z4LRtLYG5TX1c3Q8a33PYxARkEYJj6uYd5c9aF6azWDTLMB0FjZjouO8NYbLiVp2V3iuwLj4TpQhoUb4DPMqxaNKkp7b7nPrWhPuY3e4Og20c2aHCSzMZcrZGlltqKXKH6adOeZzOgj69C7QkBP2OX8iMAzTE2li0bXEIV5HFxwYpzQcy7N1ASilYppiWkF9wEc8JUJlk8PiSF3S8GC9FvNWkf3Kcmjz3FTNFzDmB9FQSQYxx9kivmOT1YOKna78DCZvgpiH0jVEmj","service":"/","tenant":"unknownt","_id":"54cf42aa8f1c04dc77caa5ae"},null]}
 ```
###  Deleting rule

* Request 
```
url: (DELETE  http://10.95.169.246:9090/rules/ZwMCOdUoGsxqKR0VrFeqbDPmz7PUEfl0hH9PDPlb2gje0P1vouScgvAzFTfOYuLacF5T9ZN82hTZQ1tvRzR73N8aXBj9zb7alCqePOpMKGEHFIi5zKGRIGcFpimtVgc2udIsiFoPogKe9cMohQHOpQc3zEbZs5dsGc8pJUAPncmU0FAyTX8u97t0H3xrmS1OfL4zLpU16phzjLdzRoKgn32c69hJTlNbkK9J7h2oM9Wia80mRYiNKN1CwFRYqE
FRynrOJ2oxgePFcTaEy20FqqhIdpJrVfMquUdd8Ax41JbUDeXXvORgFBnukTkRUGzrhTy58zDHcCTpHPoCb5lU9M5OlcE97OXS6fyJk9slh6C7Wq7YuInaJRBxepGn7ndRGghP8ejL5lyQlrM3hIaYyZg1Qb7vu7pXcsAurZ720UGICYmr5QJQGdfESwRZcozfbc2pldUrpLi5pFCdO28P2O2cH76o4oIFAY4rOPxFGBOMwudc8KwWtWybhxAKe9oa5U21wuD3fjgGX6zfwu21E7aFdopztkPxyyP8mIzaRN
UDjB2rY6CzRiy8PqD82QL0if0l2HjDFnxjkmAXt4UE9lIP7TlR0ZmPijA1mZ43052v37WSjJ0X0fsLy573zMpixrqy7DfeCmyCWjmjk9MrViHfSFdNg5tfTQPzeVbXoK8mdg4odZKcPGV2tKoYzCxKw6PjPtXrcVx789z4LRtLYG5TX1c3Q8a33PYxARkEYJj6uYd5c9aF6azWDTLMB0FjZjouO8NYbLiVp2V3iuwLj4TpQhoUb4DPMqxaNKkp7b7nPrWhPuY3e4Og20c2aHCSzMZcrZGlltqKXKH6adOeZz
Ogj69C7QkBP2OX8iMAzTE2li0bXEIV5HFxwYpzQcy7N1ASilYppiWkF9wEc8JUJlk8PiSF3S8GC9FvNWkf3Kcmjz3FTNFzDmB9FQSQYxx9kivmOT1YOKna78DCZvgpiH0jVEmj)
 
Header: ({'Fiware-Service': 'unknownT', 'Content-Type': 'application/json', 'Fiware-ServicePath': u'/', 'Accept': 'application/json'})
``` 
* Response 
```
status code: 200
 
Header: {'content-length': '2392', 'unica-correlator': 'ae9346a5-969e-4a50-ad28-01b0f06e8d92', 'x-content-type-options': 'nosniff', 'x-powered-by': 'Express', 'connection': 'keep-alive', 'date': 'Mon, 02 Feb 2015 09:26:02 GMT', 'content-type': 'application/json; charset=utf-8'}
 
Body: {"error":null,"data":[1,[{"code":200,"body":"{\"text\":\"context ctxt$unknownt$ select *,\\\"ZwMCOdUoGsxqKR0VrFeqbDPmz7PUEfl0hH9PDPlb2gje0P1vouScgvAzFTfOYuLacF5T9ZN82hTZQ1tvRzR73N8aXBj9zb7alCqePOpMKGEHFIi5zKGRIGcFpimtVgc2udIsiFoPogKe9cMohQHOpQc3zEbZs5dsGc8pJUAPncmU0FAyTX8u97t0H3xrmS1OfL4zLpU16phzjLdzRoKgn32c69hJTlNbkK9J7h2oM9Wia80mRYiNKN1CwFRYqEFRynrOJ2oxgePFcTaEy20FqqhIdpJrVfMquUdd8Ax41JbUDeXXvORgFBnukTkRUGzrhTy58zDHcCTpHPoCb5lU9M5OlcE97OXS6fyJk9slh6C7Wq7YuInaJRBxepGn7ndRGghP8ejL5lyQlrM3hIaYyZg1Qb7vu7pXcsAurZ720UGICYmr5QJQGdfESwRZcozfbc2pldUrpLi5pFCdO28P2O2cH76o4oIFAY4rOPxFGBOMwudc8KwWtWybhxAKe9oa5U21wuD3fjgGX6zfwu21E7aFdopztkPxyyP8mIzaRNUDjB2rY6CzRiy8PqD82QL0if0l2HjDFnxjkmAXt4UE9lIP7TlR0ZmPijA1mZ43052v37WSjJ0X0fsLy573zMpixrqy7DfeCmyCWjmjk9MrViHfSFdNg5tfTQPzeVbXoK8mdg4odZKcPGV2tKoYzCxKw6PjPtXrcVx789z4LRtLYG5TX1c3Q8a33PYxARkEYJj6uYd5c9aF6azWDTLMB0FjZjouO8NYbLiVp2V3iuwLj4TpQhoUb4DPMqxaNKkp7b7nPrWhPuY3e4Og20c2aHCSzMZcrZGlltqKXKH6adOeZzOgj69C7QkBP2OX8iMAzTE2li0bXEIV5HFxwYpzQcy7N1ASilYppiWkF9wEc8JUJlk8PiSF3S8GC9FvNWkf3Kcmjz3FTNFzDmB9FQSQYxx9kivmOT1YOKna78DCZvgpiH0jVEmj\\\" as ruleName, \\\"/\\\" as service, \\\"unknownT\\\" as tenant, *, ev.attrName_0? as attrName_0_var, ev.id?as Meter from pattern [every ev=iotEvent(cast(cast(attrName_0?,String),float)>1.5 and type=\\\"Room\\\")]\",\"timeLastStateChange\":1422869162818,\"name\":\"ZwMCOdUoGsxqKR0VrFeqbDPmz7PUEfl0hH9PDPlb2gje0P1vouScgvAzFTfOYuLacF5T9ZN82hTZQ1tvRzR73N8aXBj9zb7alCqePOpMKGEHFIi5zKGRIGcFpimtVgc2udIsiFoPogKe9cMohQHOpQc3zEbZs5dsGc8pJUAPncmU0FAyTX8u97t0H3xrmS1OfL4zLpU16phzjLdzRoKgn32c69hJTlNbkK9J7h2oM9Wia80mRYiNKN1CwFRYqEFRynrOJ2oxgePFcTaEy20FqqhIdpJrVfMquUdd8Ax41JbUDeXXvORgFBnukTkRUGzrhTy58zDHcCTpHPoCb5lU9M5OlcE97OXS6fyJk9slh6C7Wq7YuInaJRBxepGn7ndRGghP8ejL5lyQlrM3hIaYyZg1Qb7vu7pXcsAurZ720UGICYmr5QJQGdfESwRZcozfbc2pldUrpLi5pFCdO28P2O2cH76o4oIFAY4rOPxFGBOMwudc8KwWtWybhxAKe9oa5U21wuD3fjgGX6zfwu21E7aFdopztkPxyyP8mIzaRNUDjB2rY6CzRiy8PqD82QL0if0l2HjDFnxjkmAXt4UE9lIP7TlR0ZmPijA1mZ43052v37WSjJ0X0fsLy573zMpixrqy7DfeCmyCWjmjk9MrViHfSFdNg5tfTQPzeVbXoK8mdg4odZKcPGV2tKoYzCxKw6PjPtXrcVx789z4LRtLYG5TX1c3Q8a33PYxARkEYJj6uYd5c9aF6azWDTLMB0FjZjouO8NYbLiVp2V3iuwLj4TpQhoUb4DPMqxaNKkp7b7nPrWhPuY3e4Og20c2aHCSzMZcrZGlltqKXKH6adOeZzOgj69C7QkBP2OX8iMAzTE2li0bXEIV5HFxwYpzQcy7N1ASilYppiWkF9wEc8JUJlk8PiSF3S8GC9FvNWkf3Kcmjz3FTNFzDmB9FQSQYxx9kivmOT1YOKna78DCZvgpiH0jVEmj@unknownt/\",\"state\":\"DESTROYED\"}\n"},null],null]}
 ```
 
### Creating rule ###
* request 
```
url: (POST  http://10.95.169.246:9090/rules)
 
Header: {'Fiware-Service': 'unknownT', 'Content-Type': 'application/json', 'Fiware-ServicePath': u'/', 'Accept': 'application/json'}
 
Body: {"action": {"type": "<rule_type>", "template": "Element ${Meter} has value <<<${attrName_0_var}>>> \n -- <template_info>", "parameters": null}, "text": "select *,\"VYMy9KxuXGPLsWzmwx28LFT3JLkXtoSB9O7qTkNmd8W1AuWu3ifdiqT8RnNTQ798vBoPjHg7zRyLbJdZW36A7wkyNj19gGeS7EhoBJUakdw4lCi9sfhlc6PXtb65omc1EuJlRLuxLaZKBbxnRMygp2qvZHHNG3KnhqPQ9UOQW5Gzoy54Lhoc2cRM4PcfF2pVpC9ckmeR1hIrxsg54j4NlKa3pqfxOzOPFJl2rhWwkxA090a5Cb5fUeTExlWUslyXUeRujDElVhAcMfAWnW42Fa08dyra66UXjDG7JpCWcgKpDUcykLu0mXOLtcXYv6AFeN8kuqJskJC7npU78Dt2cxlXChlZDkNnHZgBLFus5c1yRN82RcoVthHfAtVqZ8LTWgRLz3UIpxmYVMIiLuTM5t3xNpZB2W2X9EJtPamnE0l7KL9MYnAAsXan82HLNNCkrTlF6XpMpDxCMaHYofXiTcUdFU2udChWG87ij3Rl3PxbRHfj4HVzjGCjlv7DFXKx5wW6PXyP27yCR8heCib2RTwOWPQyG4GgxE0dJ4NHeMue3nYIW2dh1DQU2j9QzR5uFtD6LWeAgwMcLggu49N25ErEQi0NlGzosVSmYdBU7LZpIr65Cgmty52spNVs6kl8ZiUr41FqGW2WMLuN5EltMoD9HmQaElwLxz0mmzDYDu2tc3fZZOEAESdvmqqFQBVsVDOZYAPHjvo1tW0Im7ZLQwRy39I4LODshIoIVAaUs9Wl0IcXL8U549tm4kWN7lkJ0hMfH0TCmfqSfhI1Fq3i7a0qO3yDDHB3rH7QR6Di5tWKeoT5B0g1WfVporWAmXahk8UyC01hDNxE0hH0vKjsOVaunHqt1Y3RDA03x3HuyJFTRwucteE5FMw4zEp74negGch4TGkyjFLD9VpCoI7o7tVMC94TxvdPRevVOz6UOOa59AMf1jPcjWOc7Z7w403qtXsjOByAukgvNBlEs5KA8N2bVc61B\" as ruleName, \"/\" as service, \"unknownT\" as tenant, *, ev.attrName_0? as attrName_0_var, ev.id? as Meter from pattern [every ev=iotEvent(cast(cast(attrName_0?,String),float)>1.5 and type=\"Room\")]", "name": "VYMy9KxuXGPLsWzmwx28LFT3JLkXtoSB9O7qTkNmd8W1AuWu3ifdiqT8RnNTQ798vBoPjHg7zRyLbJdZW36A7wkyNj19gGeS7EhoBJUakdw4lCi9sfhlc6PXtb65omc1EuJlRLuxLaZKBbxnRMygp2qvZHHNG3KnhqPQ9UOQW5Gzoy54Lhoc2cRM4PcfF2pVpC9ckmeR1hIrxsg54j4NlKa3pqfxOzOPFJl2rhWwkxA090a5Cb5fUeTExlWUslyXUeRujDElVhAcMfAWnW42Fa08dyra66UXjDG7JpCWcgKpDUcykLu0mXOLtcXYv6AFeN8kuqJskJC7npU78Dt2cxlXChlZDkNnHZgBLFus5c1yRN82RcoVthHfAtVqZ8LTWgRLz3UIpxmYVMIiLuTM5t3xNpZB2W2X9EJtPamnE0l7KL9MYnAAsXan82HLNNCkrTlF6XpMpDxCMaHYofXiTcUdFU2udChWG87ij3Rl3PxbRHfj4HVzjGCjlv7DFXKx5wW6PXyP27yCR8heCib2RTwOWPQyG4GgxE0dJ4NHeMue3nYIW2dh1DQU2j9QzR5uFtD6LWeAgwMcLggu49N25ErEQi0NlGzosVSmYdBU7LZpIr65Cgmty52spNVs6kl8ZiUr41FqGW2WMLuN5EltMoD9HmQaElwLxz0mmzDYDu2tc3fZZOEAESdvmqqFQBVsVDOZYAPHjvo1tW0Im7ZLQwRy39I4LODshIoIVAaUs9Wl0IcXL8U549tm4kWN7lkJ0hMfH0TCmfqSfhI1Fq3i7a0qO3yDDHB3rH7QR6Di5tWKeoT5B0g1WfVporWAmXahk8UyC01hDNxE0hH0vKjsOVaunHqt1Y3RDA03x3HuyJFTRwucteE5FMw4zEp74negGch4TGkyjFLD9VpCoI7o7tVMC94TxvdPRevVOz6UOOa59AMf1jPcjWOc7Z7w403qtXsjOByAukgvNBlEs5KA8N2bVc61B"}
 ```
* Response 
```
status code: 200
 
Header: {'content-length': '4991', 'unica-correlator': '9f512ee0-c51c-414e-a317-50b40b0da43a', 'x-content-type-options': 'nosniff', 'x-powered-by': 'Express', 'connection': 'keep-alive', 'date': 'Mon, 02 Feb 2015 09:34:08 GMT', 'content-type': 'application/json; charset=utf-8'}
 
Body: {"error":null,"data":[false,[{"code":200,"body":{"text":"create context ctxt$unknownt$ partition by tenant from iotEvent(tenant=\"unknownt\" and service=\"/\")","timeLastStateChange":1422868050718,"name":"ctxt$unknownt$","state":"STARTED"}},{"code":200,"body":{"text":"context ctxt$unknownt$ select *,\"VYMy9KxuXGPLsWzmwx28LFT3JLkXtoSB9O7qTkNmd8W1AuWu3ifdiqT8RnNTQ798vBoPjHg7zRyLbJdZW36A7wkyNj19gGeS7EhoBJUakdw4lCi9sfhlc6PXtb65omc1EuJlRLuxLaZKBbxnRMygp2qvZHHNG3KnhqPQ9UOQW5Gzoy54Lhoc2cRM4PcfF2pVpC9ckmeR1hIrxsg54j4NlKa3pqfxOzOPFJl2rhWwkxA090a5Cb5fUeTExlWUslyXUeRujDElVhAcMfAWnW42Fa08dyra66UXjDG7JpCWcgKpDUcykLu0mXOLtcXYv6AFeN8kuqJskJC7npU78Dt2cxlXChlZDkNnHZgBLFus5c1yRN82RcoVthHfAtVqZ8LTWgRLz3UIpxmYVMIiLuTM5t3xNpZB2W2X9EJtPamnE0l7KL9MYnAAsXan82HLNNCkrTlF6XpMpDxCMaHYofXiTcUdFU2udChWG87ij3Rl3PxbRHfj4HVzjGCjlv7DFXKx5wW6PXyP27yCR8heCib2RTwOWPQyG4GgxE0dJ4NHeMue3nYIW2dh1DQU2j9QzR5uFtD6LWeAgwMcLggu49N25ErEQi0NlGzosVSmYdBU7LZpIr65Cgmty52spNVs6kl8ZiUr41FqGW2WMLuN5EltMoD9HmQaElwLxz0mmzDYDu2tc3fZZOEAESdvmqqFQBVsVDOZYAPHjvo1tW0Im7ZLQwRy39I4LODshIoIVAaUs9Wl0IcXL8U549tm4kWN7lkJ0hMfH0TCmfqSfhI1Fq3i7a0qO3yDDHB3rH7QR6Di5tWKeoT5B0g1WfVporWAmXahk8UyC01hDNxE0hH0vKjsOVaunHqt1Y3RDA03x3HuyJFTRwucteE5FMw4zEp74negGch4TGkyjFLD9VpCoI7o7tVMC94TxvdPRevVOz6UOOa59AMf1jPcjWOc7Z7w403qtXsjOByAukgvNBlEs5KA8N2bVc61B\" as ruleName, \"/\" as service, \"unknownT\" as tenant, *, ev.attrName_0? as attrName_0_var, ev.id? as Meter from pattern [every ev=iotEvent(cast(cast(attrName_0?,String),float)>1.5 and type=\"Room\")]","timeLastStateChange":1422869648018,"name":"VYMy9KxuXGPLsWzmwx28LFT3JLkXtoSB9O7qTkNmd8W1AuWu3ifdiqT8RnNTQ798vBoPjHg7zRyLbJdZW36A7wkyNj19gGeS7EhoBJUakdw4lCi9sfhlc6PXtb65omc1EuJlRLuxLaZKBbxnRMygp2qvZHHNG3KnhqPQ9UOQW5Gzoy54Lhoc2cRM4PcfF2pVpC9ckmeR1hIrxsg54j4NlKa3pqfxOzOPFJl2rhWwkxA090a5Cb5fUeTExlWUslyXUeRujDElVhAcMfAWnW42Fa08dyra66UXjDG7JpCWcgKpDUcykLu0mXOLtcXYv6AFeN8kuqJskJC7npU78Dt2cxlXChlZDkNnHZgBLFus5c1yRN82RcoVthHfAtVqZ8LTWgRLz3UIpxmYVMIiLuTM5t3xNpZB2W2X9EJtPamnE0l7KL9MYnAAsXan82HLNNCkrTlF6XpMpDxCMaHYofXiTcUdFU2udChWG87ij3Rl3PxbRHfj4HVzjGCjlv7DFXKx5wW6PXyP27yCR8heCib2RTwOWPQyG4GgxE0dJ4NHeMue3nYIW2dh1DQU2j9QzR5uFtD6LWeAgwMcLggu49N25ErEQi0NlGzosVSmYdBU7LZpIr65Cgmty52spNVs6kl8ZiUr41FqGW2WMLuN5EltMoD9HmQaElwLxz0mmzDYDu2tc3fZZOEAESdvmqqFQBVsVDOZYAPHjvo1tW0Im7ZLQwRy39I4LODshIoIVAaUs9Wl0IcXL8U549tm4kWN7lkJ0hMfH0TCmfqSfhI1Fq3i7a0qO3yDDHB3rH7QR6Di5tWKeoT5B0g1WfVporWAmXahk8UyC01hDNxE0hH0vKjsOVaunHqt1Y3RDA03x3HuyJFTRwucteE5FMw4zEp74negGch4TGkyjFLD9VpCoI7o7tVMC94TxvdPRevVOz6UOOa59AMf1jPcjWOc7Z7w403qtXsjOByAukgvNBlEs5KA8N2bVc61B@unknownt/","state":"STARTED"}},null],{"action":{"type":"<rule_type>","template":"Element ${Meter} has value <<<${attrName_0_var}>>> \n -- <template_info>","parameters":null},"text":"select *,\"VYMy9KxuXGPLsWzmwx28LFT3JLkXtoSB9O7qTkNmd8W1AuWu3ifdiqT8RnNTQ798vBoPjHg7zRyLbJdZW36A7wkyNj19gGeS7EhoBJUakdw4lCi9sfhlc6PXtb65omc1EuJlRLuxLaZKBbxnRMygp2qvZHHNG3KnhqPQ9UOQW5Gzoy54Lhoc2cRM4PcfF2pVpC9ckmeR1hIrxsg54j4NlKa3pqfxOzOPFJl2rhWwkxA090a5Cb5fUeTExlWUslyXUeRujDElVhAcMfAWnW42Fa08dyra66UXjDG7JpCWcgKpDUcykLu0mXOLtcXYv6AFeN8kuqJskJC7npU78Dt2cxlXChlZDkNnHZgBLFus5c1yRN82RcoVthHfAtVqZ8LTWgRLz3UIpxmYVMIiLuTM5t3xNpZB2W2X9EJtPamnE0l7KL9MYnAAsXan82HLNNCkrTlF6XpMpDxCMaHYofXiTcUdFU2udChWG87ij3Rl3PxbRHfj4HVzjGCjlv7DFXKx5wW6PXyP27yCR8heCib2RTwOWPQyG4GgxE0dJ4NHeMue3nYIW2dh1DQU2j9QzR5uFtD6LWeAgwMcLggu49N25ErEQi0NlGzosVSmYdBU7LZpIr65Cgmty52spNVs6kl8ZiUr41FqGW2WMLuN5EltMoD9HmQaElwLxz0mmzDYDu2tc3fZZOEAESdvmqqFQBVsVDOZYAPHjvo1tW0Im7ZLQwRy39I4LODshIoIVAaUs9Wl0IcXL8U549tm4kWN7lkJ0hMfH0TCmfqSfhI1Fq3i7a0qO3yDDHB3rH7QR6Di5tWKeoT5B0g1WfVporWAmXahk8UyC01hDNxE0hH0vKjsOVaunHqt1Y3RDA03x3HuyJFTRwucteE5FMw4zEp74negGch4TGkyjFLD9VpCoI7o7tVMC94TxvdPRevVOz6UOOa59AMf1jPcjWOc7Z7w403qtXsjOByAukgvNBlEs5KA8N2bVc61B\" as ruleName, \"/\" as service, \"unknownT\" as tenant, *, ev.attrName_0? as attrName_0_var, ev.id? as Meter from pattern [every ev=iotEvent(cast(cast(attrName_0?,String),float)>1.5 and type=\"Room\")]","name":"VYMy9KxuXGPLsWzmwx28LFT3JLkXtoSB9O7qTkNmd8W1AuWu3ifdiqT8RnNTQ798vBoPjHg7zRyLbJdZW36A7wkyNj19gGeS7EhoBJUakdw4lCi9sfhlc6PXtb65omc1EuJlRLuxLaZKBbxnRMygp2qvZHHNG3KnhqPQ9UOQW5Gzoy54Lhoc2cRM4PcfF2pVpC9ckmeR1hIrxsg54j4NlKa3pqfxOzOPFJl2rhWwkxA090a5Cb5fUeTExlWUslyXUeRujDElVhAcMfAWnW42Fa08dyra66UXjDG7JpCWcgKpDUcykLu0mXOLtcXYv6AFeN8kuqJskJC7npU78Dt2cxlXChlZDkNnHZgBLFus5c1yRN82RcoVthHfAtVqZ8LTWgRLz3UIpxmYVMIiLuTM5t3xNpZB2W2X9EJtPamnE0l7KL9MYnAAsXan82HLNNCkrTlF6XpMpDxCMaHYofXiTcUdFU2udChWG87ij3Rl3PxbRHfj4HVzjGCjlv7DFXKx5wW6PXyP27yCR8heCib2RTwOWPQyG4GgxE0dJ4NHeMue3nYIW2dh1DQU2j9QzR5uFtD6LWeAgwMcLggu49N25ErEQi0NlGzosVSmYdBU7LZpIr65Cgmty52spNVs6kl8ZiUr41FqGW2WMLuN5EltMoD9HmQaElwLxz0mmzDYDu2tc3fZZOEAESdvmqqFQBVsVDOZYAPHjvo1tW0Im7ZLQwRy39I4LODshIoIVAaUs9Wl0IcXL8U549tm4kWN7lkJ0hMfH0TCmfqSfhI1Fq3i7a0qO3yDDHB3rH7QR6Di5tWKeoT5B0g1WfVporWAmXahk8UyC01hDNxE0hH0vKjsOVaunHqt1Y3RDA03x3HuyJFTRwucteE5FMw4zEp74negGch4TGkyjFLD9VpCoI7o7tVMC94TxvdPRevVOz6UOOa59AMf1jPcjWOc7Z7w403qtXsjOByAukgvNBlEs5KA8N2bVc61B","service":"/","tenant":"unknownt","_id":"54cf44908f1c04dc77caa5af"},null]}
 ```
### Deleting rule 
* Request 
```
url: (DELETE  http://10.95.169.246:9090/rules/VYMy9KxuXGPLsWzmwx28LFT3JLkXtoSB9O7qTkNmd8W1AuWu3ifdiqT8RnNTQ798vBoPjHg7zRyLbJdZW36A7wkyNj19gGeS7EhoBJUakdw4lCi9sfhlc6PXtb65omc1EuJlRLuxLaZKBbxnRMygp2qvZHHNG3KnhqPQ9UOQW5Gzoy54Lhoc2cRM4PcfF2pVpC9ckmeR1hIrxsg54j4NlKa3pqfxOzOPFJl2rhWwkxA090a5Cb5fUeTExlWUslyXUeRujDElVhAcMfAWnW42Fa08dyra66UXjDG7JpCWcgKpDUcykLu0mXOLtcXYv6AFeN8kuqJskJC7npU78Dt2cxlXChlZDkNnHZgBLFus5c1yRN82RcoVthHfAtVqZ8LTWgRLz3UIpxmYVMIiLuTM5t3xNpZB2W2X9EJtPamnE0l7KL9MYnAAsXan82HLNNCkrTlF6XpMpDxCMaHYofXiTcUdFU2udChWG87ij3Rl3PxbRHfj4HVzjGCjlv7DFXKx5wW6PXyP27yCR8heCib2RTwOWPQyG4GgxE0dJ4NHeMue3nYIW2dh1DQU2j9QzR5uFtD6LWeAgwMcLggu49N25ErEQi0NlGzosVSmYdBU7LZpIr65Cgmty52spNVs6kl8ZiUr41FqGW2WMLuN5EltMoD9HmQaElwLxz0mmzDYDu2tc3fZZOEAESdvmqqFQBVsVDOZYAPHjvo1tW0Im7ZLQwRy39I4LODshIoIVAaUs9Wl0IcXL8U549tm4kWN7lkJ0hMfH0TCmfqSfhI1Fq3i7a0qO3yDDHB3rH7QR6Di5tWKeoT5B0g1WfVporWAmXahk8UyC01hDNxE0hH0vKjsOVaunHqt1Y3RDA03x3HuyJFTRwucteE5FMw4zEp74negGch4TGkyjFLD9VpCoI7o7tVMC94TxvdPRevVOz6UOOa59AMf1jPcjWOc7Z7w403qtXsjOByAukgvNBlEs5KA8N2bVc61B
 
Header: {'Fiware-Service': 'unknownT', 'Content-Type': 'application/json', 'Fiware-ServicePath': u'/', 'Accept': 'application/json'}
 
Body: ()
 ```
* Response 
```
status code: 200
 
Header: {'content-length': '2394', 'unica-correlator': 'c31c1592-df6c-423e-915f-5fa369e8fd40', 'x-content-type-options': 'nosniff', 'x-powered-by': 'Express', 'connection': 'keep-alive', 'date': 'Mon, 02 Feb 2015 09:34:08 GMT', 'content-type': 'application/json; charset=utf-8'}
 
Body: {"error":null,"data":[0,[{"code":200,"body":"{\"text\":\"context ctxt$unknownt$ select *,\\\"VYMy9KxuXGPLsWzmwx28LFT3JLkXtoSB9O7qTkNmd8W1AuWu3ifdiqT8RnNTQ798vBoPjHg7zRyLbJdZW36A7wkyNj19gGeS7EhoBJUakdw4lCi9sfhlc6PXtb65omc1EuJlRLuxLaZKBbxnRMygp2qvZHHNG3KnhqPQ9UOQW5Gzoy54Lhoc2cRM4PcfF2pVpC9ckmeR1hIrxsg54j4NlKa3pqfxOzOPFJl2rhWwkxA090a5Cb5fUeTExlWUslyXUeRujDElVhAcMfAWnW42Fa08dyra66UXjDG7JpCWcgKpDUcykLu0mXOLtcXYv6AFeN8kuqJskJC7npU78Dt2cxlXChlZDkNnHZgBLFus5c1yRN82RcoVthHfAtVqZ8LTWgRLz3UIpxmYVMIiLuTM5t3xNpZB2W2X9EJtPamnE0l7KL9MYnAAsXan82HLNNCkrTlF6XpMpDxCMaHYofXiTcUdFU2udChWG87ij3Rl3PxbRHfj4HVzjGCjlv7DFXKx5wW6PXyP27yCR8heCib2RTwOWPQyG4GgxE0dJ4NHeMue3nYIW2dh1DQU2j9QzR5uFtD6LWeAgwMcLggu49N25ErEQi0NlGzosVSmYdBU7LZpIr65Cgmty52spNVs6kl8ZiUr41FqGW2WMLuN5EltMoD9HmQaElwLxz0mmzDYDu2tc3fZZOEAESdvmqqFQBVsVDOZYAPHjvo1tW0Im7ZLQwRy39I4LODshIoIVAaUs9Wl0IcXL8U549tm4kWN7lkJ0hMfH0TCmfqSfhI1Fq3i7a0qO3yDDHB3rH7QR6Di5tWKeoT5B0g1WfVporWAmXahk8UyC01hDNxE0hH0vKjsOVaunHqt1Y3RDA03x3HuyJFTRwucteE5FMw4zEp74negGch4TGkyjFLD9VpCoI7o7tVMC94TxvdPRevVOz6UOOa59AMf1jPcjWOc7Z7w403qtXsjOByAukgvNBlEs5KA8N2bVc61B\\\" as ruleName, \\\"/\\\" as service, \\\"unknownT\\\" as tenant, *, ev.attrName_0? as attrName_0_var, ev.id?as Meter from pattern [every ev=iotEvent(cast(cast(attrName_0?,String),float)>1.5 and type=\\\"Room\\\")]\",\"timeLastStateChange\":1422869648318,\"name\":\"VYMy9KxuXGPLsWzmwx28LFT3JLkXtoSB9O7qTkNmd8W1AuWu3ifdiqT8RnNTQ798vBoPjHg7zRyLbJdZW36A7wkyNj19gGeS7EhoBJUakdw4lCi9sfhlc6PXtb65omc1EuJlRLuxLaZKBbxnRMygp2qvZHHNG3KnhqPQ9UOQW5Gzoy54Lhoc2cRM4PcfF2pVpC9ckmeR1hIrxsg54j4NlKa3pqfxOzOPFJl2rhWwkxA090a5Cb5fUeTExlWUslyXUeRujDElVhAcMfAWnW42Fa08dyra66UXjDG7JpCWcgKpDUcykLu0mXOLtcXYv6AFeN8kuqJskJC7npU78Dt2cxlXChlZDkNnHZgBLFus5c1yRN82RcoVthHfAtVqZ8LTWgRLz3UIpxmYVMIiLuTM5t3xNpZB2W2X9EJtPamnE0l7KL9MYnAAsXan82HLNNCkrTlF6XpMpDxCMaHYofXiTcUdFU2udChWG87ij3Rl3PxbRHfj4HVzjGCjlv7DFXKx5wW6PXyP27yCR8heCib2RTwOWPQyG4GgxE0dJ4NHeMue3nYIW2dh1DQU2j9QzR5uFtD6LWeAgwMcLggu49N25ErEQi0NlGzosVSmYdBU7LZpIr65Cgmty52spNVs6kl8ZiUr41FqGW2WMLuN5EltMoD9HmQaElwLxz0mmzDYDu2tc3fZZOEAESdvmqqFQBVsVDOZYAPHjvo1tW0Im7ZLQwRy39I4LODshIoIVAaUs9Wl0IcXL8U549tm4kWN7lkJ0hMfH0TCmfqSfhI1Fq3i7a0qO3yDDHB3rH7QR6Di5tWKeoT5B0g1WfVporWAmXahk8UyC01hDNxE0hH0vKjsOVaunHqt1Y3RDA03x3HuyJFTRwucteE5FMw4zEp74negGch4TGkyjFLD9VpCoI7o7tVMC94TxvdPRevVOz6UOOa59AMf1jPcjWOc7Z7w403qtXsjOByAukgvNBlEs5KA8N2bVc61B@unknownt/\",\"state\":\"DESTROYED\"}\n"},null],null]}
 ```

### PR DESCRIPTION
**Pull request by crbrox**
Fixes #44 and #15 
Add validation for rule names

@fgalan @dmoranj  

FYI @iariasleon

### CODE REVIEW

File: lib/models/rules.js [hunk 1]
```diff
@@ -29,18 +29,23 @@ var util = require('util'),
     myutils = require('../myutils'),
     noSignal = require('./noSignal'),
     actions = require('./actions'),
+    namePattern = /^[a-zA-Z0-9_-]+$/,
+    MaxNameLength = 50,
```
Comment (fgalan) [inline lib/models/rules.js]: I understand that this PR enforces a name lengtha and a valid characters set. This should be included in the documentation (corresponding .md file, not sure which one should be the best one right now...).

Comment (crbrox) [inline lib/models/rules.js]: Fixed 0a4a105

**Comment by fgalan** [comment]
LGTM (passing the ball to @dmoranj for final LGTM + merge + delete branch)

**Comment by dmoranj** [comment]
LGTM
